CREATE TABLE HANBIT.MEMBER
(
   MEMBER_ID      INT NOT NULL,
   MEMBER_NAME    VARCHAR2 (100) NOT NULL,
   MEMBER_EMAIL   VARCHAR2 (200) NOT NULL,
   MEMBER_PW      VARCHAR2 (200) NOT NULL,
   PRIMARY KEY (MEMBER_ID),
   CONSTRAINT U_MEMBER_EMAIL UNIQUE (MEMBER_EMAIL)
);
