CREATE TABLE SCHEDULE
(
   SCHEDULE_ID   VARCHAR2 (20) PRIMARY KEY,
   TITLE         VARCHAR2 (200) NOT NULL,
   MEMO          VARCHAR2 (2000),
   START_DT      VARCHAR2 (20) NOT NULL,
   END_DT        VARCHAR2 (20) NOT NULL
);